name: Designspiration
favicon: null
layout_spectrum: 0.850966566009447
typography_spectrum: 0.6679442396853119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4725941950455308
  lightness: 0.6397774438373744
  saturation: 0.6582508869469166
  rhythmicContrast: 0.36056396109052
purpose: []
